### ISSUE TITLE
Maquette Interface

### ISSUE THREAD

**Issue by tholeb** [TLBail/biotrace#1]
# Maquette:
- [x] Test communication avec un automate: reprendre par exemple EasyModbusTCP
- [x] Sauvegarde des fichiers de configuration de la webdyn: penser aussi la fonctionnalité de consultation du fichier   de configuration et à la modification.
- [x] Suivi de logs
- [x] Pont bascule
- [x] Emulation de la webdyn
- [x] Configuration général: prévoir une maquette pour pouvoir spécifier les adresse des FTP par exemple

**Comment by TLBail** [comment]
868ea40 Interface: fichiers de configuration - Sh1nc0
ea1ad50 Interface: test communications - Sh1nc0
e76d8a9 fix interface - Sh1nc0

Nickel pour l'interface des sauvegarde de  fichier de configuration. 
Il va falloir expliciter que, pour faciliter la gestion des différents fichiers de configuration, chaque sauvegarde a un nom, mais que par défaut, leur nom correspond à leur date de sauvegarde.
