### ISSUE TITLE
Définir les endpoint et protocole de communication pour l'interface test communication

### ISSUE THREAD

**Issue by TLBail** [TLBail/biotrace#25]
Connexion à la Webdyn :
- IP et port

Retourne le succès de la connexion,
fournit un identifiant de session utilisé pour les logs.

Logs :
- Affiche les logs d'une session à partir de son identifiant.

Websocket :
- Lecture de données.

En paramètre, l'identifiant de session pour les logs et les paramètres de la lecture du registre.
Renvoie l'adresse du registre, la taille, le type, et la valeur lue.

**Comment by Sh1nc0** [comment]
WebSocket:


client vers serveur
* {action: "connect", ip:"", port: ""} -> {action: "connect", ip:"", port: "", status: "Success|Denied|Error", data: "logged at 127.0.0.1 on port 502"}

* {action: "read",  type: "coil", addr: "0", count= "1"} -> {action: "read", type: "coil",  addr: "0", count= "1", status: "Succes|Denied|Fail", data: "1"}}

**Comment by Sh1nc0** [comment]
**Connection:**

- **Request:**
{
"action": "connect",
"ip": "ip",
"port": 502
}

- **Response:**
{
"action": "connect",
"status":  True|False,
"data": "Connect to {ip}:{port}" | "Failed to connect to {ip}:{port}"
}


**Disconnection:**

- **Request:**
{
action: "disconnect"
}

- **Response:**
{
action: "disconnect",
"status":  True|False,
"data": "Diconnected" | "Not connected"
}

**Read:**

- **Request:**
{
"action": "read",
"type": "coil" | "holding" | "input" | "discrete",
"address": 0,
"count": 10
}

- **Response:**
{
"action": "read",
"status":  True|False,
"type": "coil" | "holding" | "input" | "discrete",
"address": 0,
"count": 10,
"data": ""
}
