### ISSUE TITLE
Définir les endpoint et protocole de communication pour l'interface Fichiers de configuration de la webdyn

### ISSUE THREAD

**Issue by TLBail** [TLBail/biotrace#26]
@tholeb tu peut mettre ce qu'on à dit en réunion et fermé l'issue

**Comment by tholeb** [comment]
CRUD pour tout le système de redondance de fichier (#3). Ça concerne donc les fichiers de logs et de configuration de la webdyn.

**Comment by tholeb** [comment]
Plus long le noms stp
