### ISSUE TITLE
Définition de l'api et de la BDD

### ISSUE THREAD

**Issue by TLBail** [TLBail/biotrace#3]
https://dbdiagram.io/

**Comment by TLBail** [comment]
@tholeb  tu vois si il y a vraiment une Api vue qu'on peut rendre la page côté serveur 
si il y a juste une BDD renomme l'issue "Définition de la BDD"

**Comment by tholeb** [comment]
![image](https://github.com/TLBail/biotrace/assets/43311443/9d57797e-8b50-436d-864e-dde100e77465)
LGTM
